### ISSUE TITLE
[Bucket permutations] Migrating list from Sandcastle

### ISSUE THREAD

**Issue by yasinS** [tomdev/teh_s3_bucketeers#3]
Hi @tomdev,

First, just wanted to say great work with Bucketeers. I've decided to cease development of my [Sandcastle](https://github.com/yasinS/sandcastle) tool; please feel free to incorporate the extended bucket prefix list from the project (some are already present in `common-bucket-prefixes.txt`). A de-duplicated version can be found below:

https://gist.github.com/yasinS/9e77cecd2fe8b275006f0436c6443a13

Thanks!

**Comment by tomdev** [comment]
Thanks @yasinS 

I just added the missing prefixes from your list!

**Comment by yasinS** [comment]
No problem @tomdev 🙂
